name: Endgame Alpha
authors: ChemtrailOperator
homepage: https://github.com/chemtrailoperator/Endgame-Alpha_EndlessSky
license: GPL-3.0-or-later
version: v0.8
shortDescription: Content and flavor plugin that adds a story line as a Navy officer in an Alpha war.
description: This plugin adds content for a Navy officer story line, in an Alpha war
  that starts in the South. Includes several new ships and outfits, and adds flavor
  to the Navy.
url: https://github.com/chemtrailoperator/Endgame-Alpha_EndlessSky/releases/download/v0.8/Endgame-Alpha_EndlessSky_v0.8.zip
iconUrl: https://github.com/chemtrailoperator/Endgame-Alpha_EndlessSky/raw/v0.8/pluginthumbnail.png
autoupdate:
  type: tag
  url: https://github.com/chemtrailoperator/Endgame-Alpha_EndlessSky/releases/download/$version/Endgame-Alpha_EndlessSky_$version.zip
  iconUrl: https://github.com/chemtrailoperator/Endgame-Alpha_EndlessSky/raw/$version/pluginthumbnail.png
