name: fleet.mercy
authors: zuckung
homepage: https://github.com/zuckung/endless-sky-plugins
license: MIT
version: v1.0.0-fleet.mercy
shortDescription: Adds the disables personality to all fleets that do not already have it, increasing the likelihood of ships being disabled rather than destroyed during AI vs. AI combat.
description: Adds the disables personality to all fleets that do not already have it, increasing the likelihood of ships being disabled rather than destroyed during AI vs. AI combat. See the README for more details.
url: https://github.com/zuckung/endless-sky-plugins/releases/download/v1.0.0-fleet.mercy/fleet.mercy.zip
iconUrl: https://raw.githubusercontent.com/zuckung/endless-sky-plugins/v1.0.0-fleet.mercy/myplugins/fleet.mercy/icon.png
autoupdate:
  type: tag
  regex: ^.*-fleet.mercy$
  url: https://github.com/zuckung/endless-sky-plugins/releases/download/$version/fleet.mercy.zip
  iconUrl: https://raw.githubusercontent.com/zuckung/endless-sky-plugins/$version/myplugins/fleet.mercy/icon.png
