name: High DPI Continuous
authors: Michael Zahniser
homepage: https://github.com/endless-sky/endless-sky-high-dpi
license: CC-BY-SA-4.0
version: e7f189579a9e2f4e49513dcadb8c9b285a88e837
shortDescription: High-DPI graphics for Endless Sky.
description: This plugin contains double resolution graphics, which are only used
  if you have a high-dpi monitor or if you set the zoom level above 100%. This will
  roughly double the amount of memory used by the game.
url: https://github.com/endless-sky/endless-sky-high-dpi/archive/e7f189579a9e2f4e49513dcadb8c9b285a88e837.zip
iconUrl: https://github.com/endless-sky/endless-sky-high-dpi/raw/e7f189579a9e2f4e49513dcadb8c9b285a88e837/icon.png
autoupdate:
  type: commit
  url: https://github.com/endless-sky/endless-sky-high-dpi/archive/$version.zip
  iconUrl: https://github.com/endless-sky/endless-sky-high-dpi/raw/$version/icon.png
