name: High DPI Continuous
authors: Michael Zahniser
homepage: https://github.com/endless-sky/endless-sky-high-dpi
license: CC-BY-SA-4.0
version: bd27c0753b74ef8f1f5833c7820a2c99cb68d994
shortDescription: High-DPI graphics for Endless Sky.
description: This plugin contains double resolution graphics, which are only used
  if you have a high-dpi monitor or if you set the zoom level above 100%. This will
  roughly double the amount of memory used by the game.
url: https://github.com/endless-sky/endless-sky-high-dpi/archive/bd27c0753b74ef8f1f5833c7820a2c99cb68d994.zip
iconUrl: https://github.com/endless-sky/endless-sky-high-dpi/raw/bd27c0753b74ef8f1f5833c7820a2c99cb68d994/icon.png
autoupdate:
  type: commit
  url: https://github.com/endless-sky/endless-sky-high-dpi/archive/$version.zip
  iconUrl: https://github.com/endless-sky/endless-sky-high-dpi/raw/$version/icon.png
