name: Interstellar Paint
authors: mOctave
homepage: https://github.com/mOctave/interstellar-paint/
license: AGPL-3.0-or-later
version: v0.1.0
shortDescription: A immersion-friendly way of reswizzling your fleet from the job board.
description: Ever wanted a way to get your ship repainted without annoying fourth wall
  breaks? Well, here it is—the galaxy's premier paint suppliers are at your fingertips...
  and they even brought some new swizzles along for the ride.
url: https://github.com/mOctave/interstellar-paint/archive/refs/tags/v0.1.0.zip
iconUrl: https://raw.githubusercontent.com/mOctave/interstellar-paint/v0.1.0/icon.png
autoupdate:
  type: tag
  url: https://github.com/mOctave/interstellar-paint/archive/refs/tags/$version.zip
  iconUrl: https://raw.githubusercontent.com/mOctave/interstellar-paint/$version/icon.png
