name: vague.improvements
authors: zuckung
homepage: https://github.com/zuckung/endless-sky-plugins
license: MIT
version: v1.0.2-vague.improvements
shortDescription: A bunch of small QoL adjustment plugins. Just delete the unwanted
  and enjoy the wanted tweaks. See the README for details.
description: A bunch of small QoL adjustment plugins. Just delete the unwanted and
  enjoy the wanted tweaks. See the README for details.
url: https://github.com/zuckung/endless-sky-plugins/releases/download/v1.0.2-vague.improvements/vague.improvements.zip
iconUrl: https://raw.githubusercontent.com/zuckung/endless-sky-plugins/v1.0.2-vague.improvements/myplugins/vague.improvements/icon.png
autoupdate:
  type: tag
  regex: ^.*-vague.improvements$
  url: https://github.com/zuckung/endless-sky-plugins/releases/download/$version/vague.improvements.zip
  iconUrl: https://raw.githubusercontent.com/zuckung/endless-sky-plugins/$version/myplugins/vague.improvements/icon.png
