name: Voidborne
authors: heasdir
homepage: https://github.com/heasdir/voidborne-plugin
license: Apache-2.0
version: v1.0
shortDescription: Voidborne is a plugin with 2 new factions.
description: Voidborne consists of two new ailen Factions. These factions are the
  Voidborne and Devourers.
url: https://github.com/heasdir/voidborne-plugin/archive/refs/tags/v1.0.zip
autoupdate:
  type: tag
  url: https://github.com/heasdir/voidborne-plugin/archive/refs/tags/$version.zip
